[#37958] Add Revit 2022 support
opf/openproject-revit-add-in pull request #16
Opened 2021-07-07 14:54 UTC by Kharonus

- https://community.openproject.org/work_packages/37958

2021-07-07 15:17 UTC, GeorgDangl requested changes
I think you also need to update the installer script to generate an option to install the plugin for Revit 2022

2021-07-07 16:03 UTC, Kharonus commented
> I think you also need to update the installer script to generate an option to install the plugin for Revit 2022

Definitely, thanks for the hint. Wasn't aware yet of this implication.

2021-07-08 14:27 UTC, GeorgDangl approved these changes

2021-07-12 15:23 UTC, wielinde approved these changes

2021-07-13 13:29 UTC, merged